# Generated by Django 4.2.20 on 2025-03-30 10:19

from django.db import migrations
import users.user_manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.user_manager.UserManager()),
            ],
        ),
    ]
