# Generated by Django 4.2.20 on 2025-04-05 09:48

from django.db import migrations
import django_resized.forms
import utils.photo_path


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[200, 200], upload_to=utils.photo_path.get_photo_path_name),
        ),
    ]
