# Generated by Django 4.2.20 on 2025-04-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_post_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='teaser',
        ),
    ]
