# Generated by Django 4.2.20 on 2025-04-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_content_post_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='teaser',
            field=models.CharField(max_length=250),
        ),
    ]
