# Generated by Django 4.2.20 on 2025-04-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text='The content of the post', null=True),
        ),
    ]
